#!/bin/bash

VERSION=2.0.6
# Modify per your setup.  If MAPLE is already defined, it uses the definition.
MAPLE=${MAPLE:-/usr/local/share/maple/15/bin/maple}
# The escaped backslashes are there to allow this work with the maple script.  
MLA="\\\"mdcs-installer-$VERSION.mla\\\""
$MAPLE -c "march(open,$MLA)" -c done
