#!/bin/bash

# This script launches pmaple, a binary that provides an enhanced
# pipeline communication with the Maple engine, using OpenMaple.

# It uses a single environmental variable, MAPLE_INCLUDE_PATH,
# that specifies directories to be searched for files specified
# in $include directives.  Multiple directories are separated
# by commas.

# Assign and export LD_LIBRARY_PATH to specify the libraries
# against which pmaple was built.

export LD_LIBRARY_PATH=$(getlibpath)

# Assign the include path

if [ "${MAPLE_INCLUDE_PATH}" ]; then
    INCLUDES="-I ${MAPLE_INCLUDE_PATH}"
else
    INCLUDES=
fi

pmaple ${INCLUDES} "$@"