#!/bin/bash

script="$0"
scriptdir="${0%/*}"

# Return a colon (:) separated list of Maple binary directories.
# The environmental variable MAPLE_ROOT points to the directory
# where Maple is installed.

SYSTYPE="$(${scriptdir}/maple.system.type)"
MAPLE_BIN=${MAPLE_ROOT}/internal/${SYSTYPE}

# Add binary directories from Maple toolboxes

TOOLBOX_BIN_DIRS="$(ls --directory ${MAPLE_ROOT}/toolbox/*/${SYSTYPE})"

if [ -z "${TOOLBOX_BIN_DIRS}" ]; then
    LD_LIBRARY_PATH="${MAPLE_BIN}"
else
    LD_LIBRARY_PATH="${MAPLE_BIN}:${TOOLBOX_BIN_DIRS}"
fi

echo "${LD_LIBRARY_PATH}"

exit 0
