#!/bin/bash

# Return a colon (:) separated list of Maple binary directories.
# The environmental variable MAPLE_ROOT points to the directory
# where Maple is installed.

SYSTYPE="$(maple.system.type)"
MAPLE_BIN=${MAPLE_ROOT}/internal/${SYSTYPE}

# Check whether MAPLE_BIN has subdirectories, 
# if so assign them to EXTRA_MAPLE_BIN_DIRS.

if [ "$(ls -1p | sed -n '/\/$/{p;q}')" ]; then
    EXTRA_MAPLE_BIN_DIRS="$(ls -1d ${MAPLE_BIN}/*/ | tr '
' ':')"
    if [ "$EXTRA_MAPLE_BIN_DIRS" = ":" ]; then
	EXTRA_MAPLE_BIN_DIRS=""
    fi
else
    EXTRA_MAPLE_BIN_DIRS=""
fi

echo ${EXTRA_MAPLE_BIN_DIRS}${MAPLE_BIN}:${MAPLE_ROOT}/toolbox/MapleSim/${SYSTYPE}

exit 0


